// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0m1gZ9w2YXyxlg2MsNl6ReDyK7fjiRY',
    appId: '1:847960787378:web:5eca4a849fb3f71405bcab',
    messagingSenderId: '847960787378',
    projectId: 'noteflow-11c17',
    authDomain: 'noteflow-11c17.firebaseapp.com',
    storageBucket: 'noteflow-11c17.firebasestorage.app',
    measurementId: 'G-VSRB9139H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWs8e7GIDFDg-xYSPVPSF9L0X6JHHAJM',
    appId: '1:847960787378:android:1d76c97ad555260905bcab',
    messagingSenderId: '847960787378',
    projectId: 'noteflow-11c17',
    storageBucket: 'noteflow-11c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVjoqMz53t6mmnIwcy6W3G1I5Zomn7VY',
    appId: '1:847960787378:ios:75a97b0c1f5e04dc05bcab',
    messagingSenderId: '847960787378',
    projectId: 'noteflow-11c17',
    storageBucket: 'noteflow-11c17.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVjoqMz53t6mmnIwcy6W3G1I5Zomn7VY',
    appId: '1:847960787378:ios:75a97b0c1f5e04dc05bcab',
    messagingSenderId: '847960787378',
    projectId: 'noteflow-11c17',
    storageBucket: 'noteflow-11c17.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0m1gZ9w2YXyxlg2MsNl6ReDyK7fjiRY',
    appId: '1:847960787378:web:4cd7ff675103814c05bcab',
    messagingSenderId: '847960787378',
    projectId: 'noteflow-11c17',
    authDomain: 'noteflow-11c17.firebaseapp.com',
    storageBucket: 'noteflow-11c17.firebasestorage.app',
    measurementId: 'G-VP89JFPZ5P',
  );
}
